### ISSUE TITLE
[Main page] Notification spamming using the like button

### ISSUE THREAD

**Issue by Artideusz** [KristianWEB/fakebooker-frontend#261]
**Describe the bug**
A user that created a post gets a bunch of notifications from one user that spam likes the post.

**To Reproduce**

1. Go to the main page.
2. Spam click the like button on a post for 2-5 seconds.

**Expected behavior**
Should notify the user that created the post that the user liked only once.

**Desktop (please complete the following information):**

- Browser Chromium
- Version 81

**Additional info**
There are also errors in the console referring to GraphQL on the spammer side.

**Comment by KristianWEB** [comment]
Could you tell me what errors are you getting on the spammer side? Also do you have the desire and time to work on this together? Really interesting issue...

**Comment by Artideusz** [comment]
The output in the console is as follows:
```
ApolloError.ts:57 Uncaught (in promise) Error: GraphQL error: No matching document found for id "5ec04e7c3398d50017f80fbd" version 2 modifiedPaths "likes"
    at new t (ApolloError.ts:57)
    at Object.next (QueryManager.ts:225)
    at g (Observable.js:135)
    at w (Observable.js:179)
    at e.value (Observable.js:235)
    at observables.ts:12
    at Set.forEach (<anonymous>)
    at Object.next (observables.ts:12)
    at g (Observable.js:135)
    at w (Observable.js:179)
t @ 2.36338ad1.chunk.js:2
next @ 2.36338ad1.chunk.js:2
g @ 2.36338ad1.chunk.js:2
w @ 2.36338ad1.chunk.js:2
value @ 2.36338ad1.chunk.js:2
(anonymous) @ 2.36338ad1.chunk.js:2
next @ 2.36338ad1.chunk.js:2
g @ 2.36338ad1.chunk.js:2
w @ 2.36338ad1.chunk.js:2
value @ 2.36338ad1.chunk.js:2
g @ 2.36338ad1.chunk.js:2
w @ 2.36338ad1.chunk.js:2
value @ 2.36338ad1.chunk.js:2
(anonymous) @ 2.36338ad1.chunk.js:2
Promise.catch (async)
s.runMutation @ 2.36338ad1.chunk.js:2
s @ 2.36338ad1.chunk.js:2
p @ 2.36338ad1.chunk.js:2
(anonymous) @ 2.36338ad1.chunk.js:2
y @ 2.36338ad1.chunk.js:2
at @ 2.36338ad1.chunk.js:2
it @ 2.36338ad1.chunk.js:2
st @ 2.36338ad1.chunk.js:2
pt @ 2.36338ad1.chunk.js:2
L @ 2.36338ad1.chunk.js:2
q @ 2.36338ad1.chunk.js:2
Jt @ 2.36338ad1.chunk.js:2
Xt @ 2.36338ad1.chunk.js:2
t.unstable_runWithPriority @ 2.36338ad1.chunk.js:2
Ui @ 2.36338ad1.chunk.js:2
D @ 2.36338ad1.chunk.js:2
$t @ 2.36338ad1.chunk.js:2
```
Sometimes the error shows a different number in the version, so instead of version 2 modifiedPaths "likes", it can be version 5 or 11, not sure what that means though.

**Comment by KristianWEB** [comment]
I'm not sure either. So I guess when we are spamming the like button we should put the button on a loading state so it can be only spammed when it's ready ( i assume because of the spamming that sometimes the query is being sent without variables ). What we can do more is to only create a notification if only there is no one in db related to this post about liking ( querying all notifications by actionId -> in this case the postId ) and if there is one we don't create one which will prevent the newNotification subscription from throwing a new notification.

**Comment by KristianWEB** [comment]
Wanna work on this together? It's gonna be fun to fix it, I guess I'm tired of coding all alone this project 😄

**Comment by Artideusz** [comment]
I never worked with someone or contributed on a project, so why not :D

**Comment by KristianWEB** [comment]
Okay, what's your discord so we can chat privately between each other?

**Comment by Artideusz** [comment]
It is Arti#4962

**Comment by Artideusz** [comment]
https://discord.gg/pFbPE6
