### ISSUE TITLE
[Register Page]: User is able to use special symbols in input fields

### ISSUE THREAD

**Issue by Artideusz** [KristianWEB/fakebooker-frontend#266]
**Describe the bug**
The user is able to use special characters ( for example: ., #, /, [, ( ) in their username or email.

**To Reproduce**

1. Go to the login page.
2. Click on "sign up now".
3. Fill out the first name, last name and the email with an input containing special characters.
4. Click register

**Expected behavior**
The input given should return an error that special characters are not allowed.

**Comment by KristianWEB** [comment]
Yep, just saw a user with these symbols that created a post and if you click on his name the app throws an error. Had to urgently remove him from db, his post so the app can work.
I'm using react-hook-form for handling forms in the whole app so I suppose we are going to use their regex pattern option on the register() function so we can filter down what characters the user can type in when registering.
